[project]
name = "ComfyUI-sjnodes"
description = "Custom ComfyUI nodes"
version = "0.1.0"
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/YOUR_GITHUB_USERNAME/comfyui-simon-nodes"

[tool.comfy]
PublisherId = "simon"
DisplayName = "ComfyUI-Simon-Nodes"
Icon = ""